### ISSUE TITLE
Folder Structure

### ISSUE THREAD

**Issue by litlfred** [WorldHealthOrganization/tng-participants-dev#9]
Can we keep the structure aligned to the names of types keys as outlined here:
  https://worldhealthorganization.github.io/smart-trust/concepts_certificate_governance.html
  https://worldhealthorganization.github.io/smart-trust/concepts.html#trust-network-participant-tnp

Looking at current folder structure, let's use change "auth" to  "TLS", "up" to "UP", "csca" to "SCA", and presumably "dsc" to "DSC".

Thanks!

**Comment by litlfred** [comment]
@tence @novoelgy @ascheibal

**Comment by SchulzeStTSI** [comment]
Solved.
